name: Mirror to other git server
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://codeberg.org/katilingban/ppitables
          GIT_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
